#!/bin/sh

set -eu

cp .env.github .env

export PATH="$(pwd)/vendor/bin:$PATH"


composer install
composer wp-install --ignore-platform-req IGNORE-PLATFORM-REQ

if [ "$(wp-install --status)" = "full" ]; then
    wp-install --serve &
fi

phpunit
