name: Unit Tests
run-name: Running unit test cases
on:
  pull_request: {}
  push:
    branches: ["master"]
jobs:
  test-build-setup:
    name: "Test PR"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        php-versions: [ '7.1','7.2','7.3','7.4', '8.0', '8.1' ]
        phpunit-versions: [ 'latest' ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: UnitTests
        with:
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
