name: Run tests

on: [push, pull_request]

jobs:
    test:
        services:
            mariadb:
                image: mariadb
                ports:
                    - 3306:3306
                env:
                    MYSQL_ROOT_PASSWORD: root
                # Ensure docker waits for mariadb to start
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: "7.4"

            - uses: actions/cache@v1
              id: cache-composer
              with:
                  path: ~/.composer/cache
                  key: ${{ runner.os }}-composer

            - uses: actions/cache@v1
              id: cache-wp-cli
              with:
                  path: ~/.wp-cli/cache
                  key: ${{ runner.os }}-wp-cli
            - name: Fetch action
              id: pl
              uses: Rishabh510/Path-lister-action@master
              with:
                path: ".github/"
                type: ".yml"

            - name: Output results
              run: |
                echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
                for i in ${{ steps.pl.outputs.paths }}; do
                echo $i
                done

            - name: Run tests
              run: .github/run-tests
